version: '3.1'

services:

  signup-db:
    image: dak4dotnet/signup-db
    build:
      context: ..
      dockerfile: ./docker/prod-dependencies/signup-db/Dockerfile

  signup-web:
    image: dak4dotnet/signup-web:v6
    build:
      context: ..
      dockerfile: ./docker/prod-dependencies/signup-web/Dockerfile