# v1 is the original monolith with SQL Server
version: '3.7'

services:
  
  signup-db:
    image: dak4dotnet/sql-server:2017
    environment:
      - sa_password=DockerCon!!!
    networks:
      - app-net

  signup-web:
    image: dak4dotnet/signup-web:v2
    ports:
      - "8020:80"
    depends_on:
      - signup-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat