# v9 has dependency checking enabled & a reusable dev database
version: '3.7'

services:
  
  signup-db:
    image: dak4dotnet/signup-db
    volumes:
      - C:\mssql:C:\data
    networks:
      - app-net

  signup-web:
    image: dak4dotnet/signup-web:v6
    environment: 
      - Dependencies:IReferenceDataLoader=SignUp.Web.ReferenceData.ApiReferenceDataLoader
      - ReferenceDataApi:Url=http://reference-data-api/api
      - Dependencies:IProspectSaveHandler=SignUp.Web.ProspectSave.AsynchronousProspectSaveHandler
      - DEPENDENCY_CHECK_ENABLED=1 
    volumes:
      - C:\web-logs:C:\logs
    labels:
      - "traefik.frontend.rule=PathPrefix:/app"
      - "traefik.frontend.priority=30"
    depends_on:
      - signup-db
      - reference-data-api
    networks:
      - app-net

  homepage:
    image: dak4dotnet/homepage
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=10"
    networks:
      - app-net

  proxy:
    image: dak4dotnet/reverse-proxy
    command: --docker --docker.endpoint=npipe:////./pipe/docker_engine --docker.watch --api
    ports:
      - "8020:80"
      - "8080:8080"
    volumes:
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine      
    networks:
      - app-net

  reference-data-api:
    image: dak4dotnet/reference-data-api
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    labels:
      - "traefik.frontend.rule=PathPrefix:/api"
      - "traefik.frontend.priority=20"
    depends_on:
      - signup-db
    networks:
      - app-net

  message-queue:
    image: nats:2.1.0
    networks:
      - app-net

  signup-save-handler:
    image: dak4dotnet/save-handler:v3
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  signup-index-handler:
    image: dak4dotnet/index-handler:v2
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:5.6.11-windowsservercore-ltsc2019
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:5.6.11-windowsservercore-ltsc2019
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

  prometheus:
    image: dak4dotnet/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: dak4dotnet/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat