apiVersion: v1
kind: Service
metadata:
  name: save-handler
spec:
  selector:    
    app: signup
    component: save-handler
  ports:
  - name: http
    port: 50505
    targetPort: 50505
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: save-handler
spec:
  selector:
    matchLabels:
      app: signup
      component: save-handler
  template:
    metadata:
      labels:
        app: signup
        component: save-handler
    spec:
      containers:
      - image: dak4dotnet/signup-save-handler-core:linux
        name: save-handler
        env:
        - name: Metrics__Enabled
          value: "true"
        - name: Metrics__Port
          value: "50505"
        ports:
        - containerPort: 50505
          name: metrics
        volumeMounts:
            - name: configs
              mountPath: "/app/configs"
              readOnly: true
      volumes:
        - name: configs
          configMap:
            name: save-handler-config
      nodeSelector:
        beta.kubernetes.io/os: linux