{
 "title": "Sign Up",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP OK Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_received_total{code=\"200\"}[12h])) without(host, instance, job, exported_instance, code)"
    }
   ]
  },
  {
   "title": "HTTP Error Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_received_total{code=\"500\"}[12h])) without(host, instance, job, exported_instance, code)"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Events Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(irate(SaveHandler_Events{status=\"received\"}[12h])) without(host, instance, job)",
     "legendFormat": "Save Events"
    },
    {
     "expr": "sum(irate(IndexHandler_Events{status=\"received\"}[12h])) without(host, instance, job)",
     "legendFormat": "Index Events"
    }
   ]
  },
  {
   "title": "Events Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(irate(SaveHandler_Events{status=\"processed\"}[12h])) without(host, instance, job)",
     "legendFormat": "Save Events"
    },
    {
     "expr": "sum(irate(IndexHandler_Events{status=\"processed\"}[12h])) without(host, instance, job)",
     "legendFormat": "Index Events"
    }
   ]
  },
  {
   "title": "Events Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(irate(SaveHandler_Events{status=\"failed\"}[12h])) without(host, instance, job)",
     "legendFormat": "Save Events"
    },
    {
     "expr": "sum(irate(IndexHandler_Events{status=\"failed\"}[12h])) without(host, instance, job)",
     "legendFormat": "Index Events"
    }
   ]
  },
  {
   "title": ".NET Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dotnet_totalmemory) without(instance)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(dotnet_total_memory_bytes) without(instance)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": ".NET CPU Time (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total) without(instance)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}